src/java/com/entities/Mantenimientos.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author Kevin Lovos
 */
@Entity
@Table(name = "mantenimientos")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Mantenimientos.findAll", query = "SELECT m FROM Mantenimientos m")
    , @NamedQuery(name = "Mantenimientos.findById", query = "SELECT m FROM Mantenimientos m WHERE m.id = :id")
    , @NamedQuery(name = "Mantenimientos.findByTipoMantenimiento", query = "SELECT m FROM Mantenimientos m WHERE m.tipoMantenimiento = :tipoMantenimiento")
    , @NamedQuery(name = "Mantenimientos.findByFechaEntrada", query = "SELECT m FROM Mantenimientos m WHERE m.fechaEntrada = :fechaEntrada")
    , @NamedQuery(name = "Mantenimientos.findByFechaSalida", query = "SELECT m FROM Mantenimientos m WHERE m.fechaSalida = :fechaSalida")
    , @NamedQuery(name = "Mantenimientos.findByFallaPrincipal", query = "SELECT m FROM Mantenimientos m WHERE m.fallaPrincipal = :fallaPrincipal")
    , @NamedQuery(name = "Mantenimientos.findByFallaSecundaria", query = "SELECT m FROM Mantenimientos m WHERE m.fallaSecundaria = :fallaSecundaria")
    , @NamedQuery(name = "Mantenimientos.findByEstado", query = "SELECT m FROM Mantenimientos m WHERE m.estado = :estado")})
public class Mantenimientos implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 50)
    @Column(name = "tipoMantenimiento")
    private String tipoMantenimiento;
    @Basic(optional = false)
    @NotNull
    @Column(name = "fechaEntrada")
    @Temporal(TemporalType.DATE)
    private Date fechaEntrada;
    @Basic(optional = false)
    @NotNull
    @Column(name = "fechaSalida")
    @Temporal(TemporalType.DATE)
    private Date fechaSalida;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 50)
    @Column(name = "fallaPrincipal")
    private String fallaPrincipal;
    @Size(max = 50)
    @Column(name = "fallaSecundaria")
    private String fallaSecundaria;
    @Basic(optional = false)
    @NotNull
    @Column(name = "estado")
    private int estado;
    @JoinColumn(name = "idTaller", referencedColumnName = "id")
    @ManyToOne(optional = false)
    private Talleres idTaller;
    @JoinColumn(name = "idVehiculo", referencedColumnName = "id")
    @ManyToOne(optional = false)
    private Vehiculos idVehiculo;

    public Mantenimientos() {
    }

    public Mantenimientos(Integer id) {
        this.id = id;
    }

    public Mantenimientos(Integer id, String tipoMantenimiento, Date fechaEntrada, Date fechaSalida, String fallaPrincipal, int estado) {
        this.id = id;
        this.tipoMantenimiento = tipoMantenimiento;
        this.fechaEntrada = fechaEntrada;
        this.fechaSalida = fechaSalida;
        this.fallaPrincipal = fallaPrincipal;
        this.estado = estado;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTipoMantenimiento() {
        return tipoMantenimiento;
    }

    public void setTipoMantenimiento(String tipoMantenimiento) {
        this.tipoMantenimiento = tipoMantenimiento;
    }

    public Date getFechaEntrada() {
        return fechaEntrada;
    }

    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }

    public Date getFechaSalida() {
        return fechaSalida;
    }

    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }

    public String getFallaPrincipal() {
        return fallaPrincipal;
    }

    public void setFallaPrincipal(String fallaPrincipal) {
        this.fallaPrincipal = fallaPrincipal;
    }

    public String getFallaSecundaria() {
        return fallaSecundaria;
    }

    public void setFallaSecundaria(String fallaSecundaria) {
        this.fallaSecundaria = fallaSecundaria;
    }

    public int getEstado() {
        return estado;
    }

    public void setEstado(int estado) {
        this.estado = 1;
    }

    public Talleres getIdTaller() {
        return idTaller;
    }

    public void setIdTaller(Talleres idTaller) {
        this.idTaller = idTaller;
    }

    public Vehiculos getIdVehiculo() {
        return idVehiculo;
    }

    public void setIdVehiculo(Vehiculos idVehiculo) {
        this.idVehiculo = idVehiculo;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Mantenimientos)) {
            return false;
        }
        Mantenimientos other = (Mantenimientos) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.entities.Mantenimientos[ id=" + id + " ]";
    }
    
}

src/java/com/controller/MantenimientosController.java
package com.controller;

import com.entities.Mantenimientos;
import com.controller.util.JsfUtil;
import com.controller.util.PaginationHelper;
import com.beans.MantenimientosFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("mantenimientosController")
@SessionScoped
public class MantenimientosController implements Serializable {

    private Mantenimientos current;
    private DataModel items = null;
    @EJB
    private com.beans.MantenimientosFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public MantenimientosController() {
    }

    public Mantenimientos getSelected() {
        if (current == null) {
            current = new Mantenimientos();
            selectedItemIndex = -1;
        }
        return current;
    }

    private MantenimientosFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Mantenimientos) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Mantenimientos();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("MantenimientosCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Mantenimientos) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("MantenimientosUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Mantenimientos) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("MantenimientosDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Mantenimientos getMantenimientos(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Mantenimientos.class)
    public static class MantenimientosControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            MantenimientosController controller = (MantenimientosController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "mantenimientosController");
            return controller.getMantenimientos(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Mantenimientos) {
                Mantenimientos o = (Mantenimientos) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Mantenimientos.class.getName());
            }
        }

    }

}

web/views/mantenimientos/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateMantenimientosTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateMantenimientosLabel_id}" for="id" style="display: none;" />
                    <h:inputText class="form-control" id="id" value="0" style="display: none;" title="#{bundle.CreateMantenimientosTitle_id}" required="true" requiredMessage="#{bundle.CreateMantenimientosRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.CreateMantenimientosLabel_tipoMantenimiento}" for="tipoMantenimiento" />
                    <h:inputText class="form-control" id="tipoMantenimiento" value="#{mantenimientosController.selected.tipoMantenimiento}" title="#{bundle.CreateMantenimientosTitle_tipoMantenimiento}" required="true" requiredMessage="#{bundle.CreateMantenimientosRequiredMessage_tipoMantenimiento}"/>
                    <h:outputLabel value="#{bundle.CreateMantenimientosLabel_fechaEntrada}" for="fechaEntrada" />
                    <p:calendar class="form-control" id="fechaEntrada" value="#{mantenimientosController.selected.fechaEntrada}" title="#{bundle.CreateMantenimientosTitle_fechaEntrada}" required="true" requiredMessage="#{bundle.CreateMantenimientosRequiredMessage_fechaEntrada}">
                        <f:convertDateTime pattern="dd/MM/yyyy" />
                    </p:calendar>
                    <h:outputLabel value="#{bundle.CreateMantenimientosLabel_fechaSalida}" for="fechaSalida" />
                    <p:calendar  class="form-control" id="fechaSalida" value="#{mantenimientosController.selected.fechaSalida}" title="#{bundle.CreateMantenimientosTitle_fechaSalida}" required="true" requiredMessage="#{bundle.CreateMantenimientosRequiredMessage_fechaSalida}">
                        <f:convertDateTime pattern="dd/MM/yyyy" />
                    </p:calendar>
                    <h:outputLabel value="#{bundle.CreateMantenimientosLabel_fallaPrincipal}" for="fallaPrincipal" />
                    <h:inputText class="form-control" id="fallaPrincipal" value="#{mantenimientosController.selected.fallaPrincipal}" title="#{bundle.CreateMantenimientosTitle_fallaPrincipal}" required="true" requiredMessage="#{bundle.CreateMantenimientosRequiredMessage_fallaPrincipal}"/>
                    <h:outputLabel value="#{bundle.CreateMantenimientosLabel_fallaSecundaria}" for="fallaSecundaria" />
                    <h:inputText class="form-control" id="fallaSecundaria" value="#{mantenimientosController.selected.fallaSecundaria}" title="#{bundle.CreateMantenimientosTitle_fallaSecundaria}" />
                    <h:outputLabel value="#{bundle.CreateMantenimientosLabel_estado}" for="estado" style="display: none;"/>
                    <h:inputText class="form-control" id="estado" value="#{mantenimientosController.selected.estado}" style="display: none;" title="#{bundle.CreateMantenimientosTitle_estado}" required="true" requiredMessage="#{bundle.CreateMantenimientosRequiredMessage_estado}"/>
                    <h:outputLabel value="#{bundle.CreateMantenimientosLabel_idTaller}" for="idTaller" />
                    <h:selectOneMenu class="form-control" id="idTaller" value="#{mantenimientosController.selected.idTaller}" title="#{bundle.CreateMantenimientosTitle_idTaller}" required="true" requiredMessage="#{bundle.CreateMantenimientosRequiredMessage_idTaller}">
                        <f:selectItems class="form-control" value="#{talleresController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateMantenimientosLabel_idVehiculo}" for="idVehiculo" />
                    <h:selectOneMenu class="form-control" id="idVehiculo" value="#{mantenimientosController.selected.idVehiculo}" title="#{bundle.CreateMantenimientosTitle_idVehiculo}" required="true" requiredMessage="#{bundle.CreateMantenimientosRequiredMessage_idVehiculo}">
                        <f:selectItems class="form-control" value="#{vehiculosController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink class="btn btn-info" action="#{mantenimientosController.create}" value="#{bundle.CreateMantenimientosSaveLink}" />
                 &nbsp;&nbsp;
                <h:commandLink class="btn btn-success" action="#{mantenimientosController.prepareList}" value="#{bundle.CreateMantenimientosShowAllLink}" immediate="true"/>
                 &nbsp;&nbsp;
                <h:link class="btn btn-light" outcome="/index" value="#{bundle.CreateMantenimientosIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/views/mantenimientos/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditMantenimientosTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditMantenimientosLabel_id}" for="id" style="display: none;" />
                    <h:inputText class="form-control" id="id" value="#{mantenimientosController.selected.id}" title="#{bundle.EditMantenimientosTitle_id}" style="display: none;" requiredMessage="#{bundle.EditMantenimientosRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.EditMantenimientosLabel_tipoMantenimiento}" for="tipoMantenimiento" />
                    <h:inputText class="form-control" id="tipoMantenimiento" value="#{mantenimientosController.selected.tipoMantenimiento}" title="#{bundle.EditMantenimientosTitle_tipoMantenimiento}" required="true" requiredMessage="#{bundle.EditMantenimientosRequiredMessage_tipoMantenimiento}"/>
                    <h:outputLabel value="#{bundle.EditMantenimientosLabel_fechaEntrada}" for="fechaEntrada" />
                    <p:calendar class="form-control" id="fechaEntrada" value="#{mantenimientosController.selected.fechaEntrada}" title="#{bundle.EditMantenimientosTitle_fechaEntrada}" required="true" requiredMessage="#{bundle.EditMantenimientosRequiredMessage_fechaEntrada}">
                        <f:convertDateTime pattern="dd/MM/yyyy" />
                    </p:calendar>
                    <h:outputLabel value="#{bundle.EditMantenimientosLabel_fechaSalida}" for="fechaSalida" />
                    <p:calendar class="form-control" id="fechaSalida" value="#{mantenimientosController.selected.fechaSalida}" title="#{bundle.EditMantenimientosTitle_fechaSalida}" required="true" requiredMessage="#{bundle.EditMantenimientosRequiredMessage_fechaSalida}">
                        <f:convertDateTime pattern="dd/MM/yyyy" />
                    </p:calendar>
                    <h:outputLabel value="#{bundle.EditMantenimientosLabel_fallaPrincipal}" for="fallaPrincipal" />
                    <h:inputText class="form-control" id="fallaPrincipal" value="#{mantenimientosController.selected.fallaPrincipal}" title="#{bundle.EditMantenimientosTitle_fallaPrincipal}" required="true" requiredMessage="#{bundle.EditMantenimientosRequiredMessage_fallaPrincipal}"/>
                    <h:outputLabel value="#{bundle.EditMantenimientosLabel_fallaSecundaria}" for="fallaSecundaria" />
                    <h:inputText class="form-control" id="fallaSecundaria" value="#{mantenimientosController.selected.fallaSecundaria}" title="#{bundle.EditMantenimientosTitle_fallaSecundaria}" />
                    <h:outputLabel value="#{bundle.EditMantenimientosLabel_estado}" for="estado" style="display: none;" />
                    <h:inputText class="form-control" id="estado" value="#{mantenimientosController.selected.estado}" title="#{bundle.EditMantenimientosTitle_estado}" style="display: none;" requiredMessage="#{bundle.EditMantenimientosRequiredMessage_estado}"/>
                    <h:outputLabel value="#{bundle.EditMantenimientosLabel_idTaller}" for="idTaller" />
                    <h:selectOneMenu class="form-control" id="idTaller" value="#{mantenimientosController.selected.idTaller}" title="#{bundle.EditMantenimientosTitle_idTaller}" required="true" requiredMessage="#{bundle.EditMantenimientosRequiredMessage_idTaller}">
                        <f:selectItems class="form-control" value="#{talleresController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditMantenimientosLabel_idVehiculo}" for="idVehiculo" />
                    <h:selectOneMenu class="form-control" id="idVehiculo" value="#{mantenimientosController.selected.idVehiculo}" title="#{bundle.EditMantenimientosTitle_idVehiculo}" required="true" requiredMessage="#{bundle.EditMantenimientosRequiredMessage_idVehiculo}">
                        <f:selectItems class="form-control" value="#{vehiculosController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink class="btn btn-info" action="#{mantenimientosController.update}" value="#{bundle.EditMantenimientosSaveLink}"/>
                 &nbsp;&nbsp;
                <h:link class="btn btn-dark" outcome="View" value="#{bundle.EditMantenimientosViewLink}"/>
                 &nbsp;&nbsp;
                <h:commandLink class="btn btn-success" action="#{mantenimientosController.prepareList}" value="#{bundle.EditMantenimientosShowAllLink}" immediate="true"/>
                 &nbsp;&nbsp;
                <h:link class="btn btn-light" outcome="/index" value="#{bundle.EditMantenimientosIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/views/mantenimientos/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="LISTADO DE MANTENIMIENTOS"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListMantenimientosEmpty}" rendered="#{mantenimientosController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{mantenimientosController.items.rowCount > 0}">
                    <h:commandLink action="#{mantenimientosController.previous}" value="#{bundle.Previous} #{mantenimientosController.pagination.pageSize}" rendered="#{mantenimientosController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{mantenimientosController.next}" value="#{bundle.Next} #{mantenimientosController.pagination.pageSize}" rendered="#{mantenimientosController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable class="table table-hover" style="width: 85%;" value="#{mantenimientosController.items}" var="item" >
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListMantenimientosTitle_tipoMantenimiento}"/>
                            </f:facet>
                            <h:outputText value="#{item.tipoMantenimiento}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListMantenimientosTitle_fechaEntrada}"/>
                            </f:facet>
                            <h:outputText value="#{item.fechaEntrada}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListMantenimientosTitle_fechaSalida}"/>
                            </f:facet>
                            <h:outputText value="#{item.fechaSalida}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListMantenimientosTitle_fallaPrincipal}"/>
                            </f:facet>
                            <h:outputText value="#{item.fallaPrincipal}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListMantenimientosTitle_fallaSecundaria}"/>
                            </f:facet>
                            <h:outputText value="#{item.fallaSecundaria}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Acciones"/>
                            </f:facet>
                            <h:commandLink class="btn btn-info btn-sm" action="#{mantenimientosController.prepareView}" value="#{bundle.ListMantenimientosViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink class="btn btn-warning btn-sm" action="#{mantenimientosController.prepareEdit}" value="#{bundle.ListMantenimientosEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink class="btn btn-danger btn-sm" action="#{mantenimientosController.destroy}" value="#{bundle.ListMantenimientosDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink class="btn btn-success" action="#{mantenimientosController.prepareCreate}" value="#{bundle.ListMantenimientosCreateLink}"/>
                 &nbsp;&nbsp;
                <h:link class="btn btn-dark" outcome="/index" value="#{bundle.ListMantenimientosIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>