src/java/com/entities/Talleres.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author Kevin Lovos
 */
@Entity
@Table(name = "talleres")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Talleres.findAll", query = "SELECT t FROM Talleres t")
    , @NamedQuery(name = "Talleres.findById", query = "SELECT t FROM Talleres t WHERE t.id = :id")
    , @NamedQuery(name = "Talleres.findByNombre", query = "SELECT t FROM Talleres t WHERE t.nombre = :nombre")
    , @NamedQuery(name = "Talleres.findByDireccion", query = "SELECT t FROM Talleres t WHERE t.direccion = :direccion")
    , @NamedQuery(name = "Talleres.findByTelefono", query = "SELECT t FROM Talleres t WHERE t.telefono = :telefono")
    , @NamedQuery(name = "Talleres.findByFallas", query = "SELECT t FROM Talleres t WHERE t.fallas = :fallas")
    , @NamedQuery(name = "Talleres.findByEstado", query = "SELECT t FROM Talleres t WHERE t.estado = :estado")})
public class Talleres implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 50)
    @Column(name = "nombre")
    private String nombre;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 100)
    @Column(name = "direccion")
    private String direccion;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 15)
    @Column(name = "telefono")
    private String telefono;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 200)
    @Column(name = "fallas")
    private String fallas;
    @Basic(optional = false)
    @NotNull
    @Column(name = "estado")
    private int estado;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "idTaller")
    private List<Mantenimientos> mantenimientosList;

    public Talleres() {
    }

    public Talleres(Integer id) {
        this.id = id;
    }

    public Talleres(Integer id, String nombre, String direccion, String telefono, String fallas, int estado) {
        this.id = id;
        this.nombre = nombre;
        this.direccion = direccion;
        this.telefono = telefono;
        this.fallas = fallas;
        this.estado = estado;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDireccion() {
        return direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getTelefono() {
        return telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getFallas() {
        return fallas;
    }

    public void setFallas(String fallas) {
        this.fallas = fallas;
    }

    public int getEstado() {
        return estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }

    @XmlTransient
    public List<Mantenimientos> getMantenimientosList() {
        return mantenimientosList;
    }

    public void setMantenimientosList(List<Mantenimientos> mantenimientosList) {
        this.mantenimientosList = mantenimientosList;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Talleres)) {
            return false;
        }
        Talleres other = (Talleres) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return nombre;
    }
    
}

src/java/com/controller/TalleresController.java
package com.controller;

import com.entities.Talleres;
import com.controller.util.JsfUtil;
import com.controller.util.PaginationHelper;
import com.beans.TalleresFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("talleresController")
@SessionScoped
public class TalleresController implements Serializable {

    private Talleres current;
    private DataModel items = null;
    @EJB
    private com.beans.TalleresFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public TalleresController() {
    }

    public Talleres getSelected() {
        if (current == null) {
            current = new Talleres();
            selectedItemIndex = -1;
        }
        return current;
    }

    private TalleresFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Talleres) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Talleres();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("TalleresCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Talleres) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("TalleresUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Talleres) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("TalleresDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Talleres getTalleres(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Talleres.class)
    public static class TalleresControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            TalleresController controller = (TalleresController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "talleresController");
            return controller.getTalleres(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Talleres) {
                Talleres o = (Talleres) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Talleres.class.getName());
            }
        }

    }

}

web/views/talleres/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateTalleresTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateTalleresLabel_id}" for="id" />
                    <h:inputText id="id" value="#{talleresController.selected.id}" title="#{bundle.CreateTalleresTitle_id}" required="true" requiredMessage="#{bundle.CreateTalleresRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.CreateTalleresLabel_nombre}" for="nombre" />
                    <h:inputText id="nombre" value="#{talleresController.selected.nombre}" title="#{bundle.CreateTalleresTitle_nombre}" required="true" requiredMessage="#{bundle.CreateTalleresRequiredMessage_nombre}"/>
                    <h:outputLabel value="#{bundle.CreateTalleresLabel_direccion}" for="direccion" />
                    <h:inputText id="direccion" value="#{talleresController.selected.direccion}" title="#{bundle.CreateTalleresTitle_direccion}" required="true" requiredMessage="#{bundle.CreateTalleresRequiredMessage_direccion}"/>
                    <h:outputLabel value="#{bundle.CreateTalleresLabel_telefono}" for="telefono" />
                    <h:inputText id="telefono" value="#{talleresController.selected.telefono}" title="#{bundle.CreateTalleresTitle_telefono}" required="true" requiredMessage="#{bundle.CreateTalleresRequiredMessage_telefono}"/>
                    <h:outputLabel value="#{bundle.CreateTalleresLabel_fallas}" for="fallas" />
                    <h:inputText id="fallas" value="#{talleresController.selected.fallas}" title="#{bundle.CreateTalleresTitle_fallas}" required="true" requiredMessage="#{bundle.CreateTalleresRequiredMessage_fallas}"/>
                    <h:outputLabel value="#{bundle.CreateTalleresLabel_estado}" for="estado" />
                    <h:inputText id="estado" value="#{talleresController.selected.estado}" title="#{bundle.CreateTalleresTitle_estado}" required="true" requiredMessage="#{bundle.CreateTalleresRequiredMessage_estado}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{talleresController.create}" value="#{bundle.CreateTalleresSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{talleresController.prepareList}" value="#{bundle.CreateTalleresShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateTalleresIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/views/talleres/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditTalleresTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditTalleresLabel_id}" for="id" />
                    <h:inputText id="id" value="#{talleresController.selected.id}" title="#{bundle.EditTalleresTitle_id}" required="true" requiredMessage="#{bundle.EditTalleresRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.EditTalleresLabel_nombre}" for="nombre" />
                    <h:inputText id="nombre" value="#{talleresController.selected.nombre}" title="#{bundle.EditTalleresTitle_nombre}" required="true" requiredMessage="#{bundle.EditTalleresRequiredMessage_nombre}"/>
                    <h:outputLabel value="#{bundle.EditTalleresLabel_direccion}" for="direccion" />
                    <h:inputText id="direccion" value="#{talleresController.selected.direccion}" title="#{bundle.EditTalleresTitle_direccion}" required="true" requiredMessage="#{bundle.EditTalleresRequiredMessage_direccion}"/>
                    <h:outputLabel value="#{bundle.EditTalleresLabel_telefono}" for="telefono" />
                    <h:inputText id="telefono" value="#{talleresController.selected.telefono}" title="#{bundle.EditTalleresTitle_telefono}" required="true" requiredMessage="#{bundle.EditTalleresRequiredMessage_telefono}"/>
                    <h:outputLabel value="#{bundle.EditTalleresLabel_fallas}" for="fallas" />
                    <h:inputText id="fallas" value="#{talleresController.selected.fallas}" title="#{bundle.EditTalleresTitle_fallas}" required="true" requiredMessage="#{bundle.EditTalleresRequiredMessage_fallas}"/>
                    <h:outputLabel value="#{bundle.EditTalleresLabel_estado}" for="estado" />
                    <h:inputText id="estado" value="#{talleresController.selected.estado}" title="#{bundle.EditTalleresTitle_estado}" required="true" requiredMessage="#{bundle.EditTalleresRequiredMessage_estado}"/>
                </h:panelGrid>
                <h:commandLink action="#{talleresController.update}" value="#{bundle.EditTalleresSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditTalleresViewLink}"/>
                <br />
                <h:commandLink action="#{talleresController.prepareList}" value="#{bundle.EditTalleresShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditTalleresIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/views/talleres/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListTalleresTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListTalleresEmpty}" rendered="#{talleresController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{talleresController.items.rowCount > 0}">
                    <h:outputText value="#{talleresController.pagination.pageFirstItem + 1}..#{talleresController.pagination.pageLastItem + 1}/#{talleresController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{talleresController.previous}" value="#{bundle.Previous} #{talleresController.pagination.pageSize}" rendered="#{talleresController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{talleresController.next}" value="#{bundle.Next} #{talleresController.pagination.pageSize}" rendered="#{talleresController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{talleresController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTalleresTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTalleresTitle_nombre}"/>
                            </f:facet>
                            <h:outputText value="#{item.nombre}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTalleresTitle_direccion}"/>
                            </f:facet>
                            <h:outputText value="#{item.direccion}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTalleresTitle_telefono}"/>
                            </f:facet>
                            <h:outputText value="#{item.telefono}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTalleresTitle_fallas}"/>
                            </f:facet>
                            <h:outputText value="#{item.fallas}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTalleresTitle_estado}"/>
                            </f:facet>
                            <h:outputText value="#{item.estado}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{talleresController.prepareView}" value="#{bundle.ListTalleresViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{talleresController.prepareEdit}" value="#{bundle.ListTalleresEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{talleresController.destroy}" value="#{bundle.ListTalleresDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{talleresController.prepareCreate}" value="#{bundle.ListTalleresCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListTalleresIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/views/talleres/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewTalleresTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewTalleresLabel_id}"/>
                    <h:outputText value="#{talleresController.selected.id}" title="#{bundle.ViewTalleresTitle_id}"/>
                    <h:outputText value="#{bundle.ViewTalleresLabel_nombre}"/>
                    <h:outputText value="#{talleresController.selected.nombre}" title="#{bundle.ViewTalleresTitle_nombre}"/>
                    <h:outputText value="#{bundle.ViewTalleresLabel_direccion}"/>
                    <h:outputText value="#{talleresController.selected.direccion}" title="#{bundle.ViewTalleresTitle_direccion}"/>
                    <h:outputText value="#{bundle.ViewTalleresLabel_telefono}"/>
                    <h:outputText value="#{talleresController.selected.telefono}" title="#{bundle.ViewTalleresTitle_telefono}"/>
                    <h:outputText value="#{bundle.ViewTalleresLabel_fallas}"/>
                    <h:outputText value="#{talleresController.selected.fallas}" title="#{bundle.ViewTalleresTitle_fallas}"/>
                    <h:outputText value="#{bundle.ViewTalleresLabel_estado}"/>
                    <h:outputText value="#{talleresController.selected.estado}" title="#{bundle.ViewTalleresTitle_estado}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{talleresController.destroyAndView}" value="#{bundle.ViewTalleresDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewTalleresEditLink}"/>
                <br />
                <h:commandLink action="#{talleresController.prepareCreate}" value="#{bundle.ViewTalleresCreateLink}" />
                <br />
                <h:commandLink action="#{talleresController.prepareList}" value="#{bundle.ViewTalleresShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewTalleresIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>